import {
  Zap,
  Droplets,
  Wind,
  Settings,
  Car,
  Bath,
  Flame,
  Shield,
} from "lucide-react";

export const infrastructureData = {
  title: "Infrastructure & Facilities",
  items: [
    {
      label: "Power Backup",
      sub: "100% DG Backup",
      status: "INSTALLED",
      statusColor: "text-emerald-500",
      icon: Zap,
      iconBg: "bg-gradient-to-br from-[#bf953f] to-[#b38728] shadow-sm shadow-[#d4af37]/20 border-none text-white",
    },
    {
      label: "Water & STP",
      sub: "Zero Discharge Plant",
      status: "CONNECTED",
      statusColor: "text-emerald-500",
      icon: Droplets,
      iconBg: "bg-gradient-to-br from-[#3B82F6] to-[#1D4ED8] shadow-sm shadow-[#3B82F6]/20 border-none text-white",
    },
    {
      label: "Central HVAC",
      sub: "Water Cooled Chillers",
      status: "INSTALLED",
      statusColor: "text-emerald-500",
      icon: Wind,
      iconBg: "bg-gradient-to-br from-[#F97316] to-[#C2410C] shadow-sm shadow-[#F97316]/20 border-none text-white",
    },
    {
      label: "Building Mgmt",
      sub: "BMS System",
      status: "ACTIVE",
      statusColor: "text-emerald-500",
      icon: Settings,
      iconBg: "bg-gradient-to-br from-[#10B981] to-[#047857] shadow-sm shadow-[#10B981]/20 border-none text-white",
    },
    {
      label: "Parking",
      sub: "Visitor & EV Charging",
      status: "3 LEVELS",
      statusColor: "text-indigo-500",
      icon: Car,
      iconBg: "bg-gradient-to-br from-[#8B5CF6] to-[#6D28D9] shadow-sm shadow-[#8B5CF6]/20 border-none text-white",
    },
    {
      label: "Common Washrooms",
      sub: "Maintained by Facility",
      status: "ALL FLOORS",
      statusColor: "text-emerald-500",
      icon: Bath,
      iconBg: "bg-gradient-to-br from-[#0EA5E9] to-[#0369A1] shadow-sm shadow-[#0EA5E9]/20 border-none text-white",
    },
    {
      label: "Fire Safety",
      sub: "Sprinklers + Hydrants",
      status: "COMPLIANT",
      statusColor: "text-emerald-500",
      icon: Flame,
      iconBg: "bg-gradient-to-br from-[#F43F5E] to-[#BE123C] shadow-sm shadow-[#F43F5E]/20 border-none text-white",
    },
    {
      label: "Security",
      sub: "24/7 CCTV + Guards",
      status: "YES",
      statusColor: "text-emerald-500",
      icon: Shield,
      iconBg: "bg-gradient-to-br from-[#14B8A6] to-[#0F766E] shadow-sm shadow-[#14B8A6]/20 border-none text-white",
    },
  ],
};
