import {
  Utensils,
  Coffee,
  Smartphone,
  Dumbbell,
  PawPrint,
  Store,
  GraduationCap,
  Scissors,
  Car,
  Wrench,
} from "lucide-react";
export interface Franchise {
  id: number;
  name: string;
  logo: string;
  investment: string;
  location: string;
  lat: number;
  lng: number;
  category: string;
  matchLevel: "selected" | "high" | "other";
  roi: string;
  established: string;
  units: number;
  breakeven: string;
  tags: string[];
  description: string;
}
export const categories = [
  "All",
  "Food & Beverage",
  "Coffee & Cafe",
  "Technology",
  "Health & Fitness",
  "Pet Services",
  "Education",
  "Beauty & Wellness",
  "Automotive",
  "Home Services",
] as const;
export const franchises: Franchise[] = [
  {
    id: 1,
    name: "Domino's Pizza",
    logo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&h=300",
    investment: "₹35L – ₹60 Lakh",
    location: "Koramangala, Bengaluru",
    lat: 55,
    lng: 45,
    category: "Food & Beverage",
    matchLevel: "selected",
    roi: "28–35%",
    established: "1960",
    units: 1920,
    breakeven: "14–18 months",
    tags: ["Top Rated", "Trending"],
    description:
      "World's leading pizza delivery franchise with proven unit economics and 60+ years of global brand trust.",
  },
  {
    id: 2,
    name: "McDonald's",
    logo: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=400&h=300",
    investment: "₹1.5 – ₹2.5 Cr",
    location: "Indiranagar, Bengaluru",
    lat: 25,
    lng: 30,
    category: "Food & Beverage",
    matchLevel: "high",
    roi: "22–30%",
    established: "1955",
    units: 40000,
    breakeven: "24–36 months",
    tags: ["Premium"],
    description:
      "Iconic global QSR brand with massive brand recall, deep operational support, and a loyal customer base.",
  },
  {
    id: 3,
    name: "Subway",
    logo: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=400&h=300",
    investment: "₹25 – ₹50 Lakh",
    location: "HSR Layout, Bengaluru",
    lat: 70,
    lng: 55,
    category: "Food & Beverage",
    matchLevel: "high",
    roi: "20–28%",
    established: "1965",
    units: 37000,
    breakeven: "18–24 months",
    tags: ["Popular"],
    description:
      "Health-conscious submarine sandwich franchise with flexible store formats and low operational overhead.",
  },
  {
    id: 4,
    name: "Cafe Coffee Day",
    logo: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&h=300",
    investment: "₹20 – ₹40 Lakh",
    location: "Jayanagar, Bengaluru",
    lat: 40,
    lng: 20,
    category: "Coffee & Cafe",
    matchLevel: "other",
    roi: "18–25%",
    established: "1996",
    units: 1750,
    breakeven: "20–28 months",
    tags: ["Indian Brand"],
    description:
      "India's favourite coffee chain with a strong loyalty base and pan-India brand recognition.",
  },
  {
    id: 5,
    name: "TechFix Hub",
    logo: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=400&h=300",
    investment: "₹50K – ₹90K",
    location: "Whitefield, Bengaluru",
    lat: 35,
    lng: 75,
    category: "Technology",
    matchLevel: "high",
    roi: "35–45%",
    established: "2019",
    units: 320,
    breakeven: "6–10 months",
    tags: ["New", "High ROI"],
    description:
      "Mobile & gadget repair franchise with low investment, high margins, and a booming after-market sector.",
  },
  {
    id: 6,
    name: "FitLife Gyms",
    logo: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=400&h=300",
    investment: "₹2L – ₹5 Lakh",
    location: "Marathahalli, Bengaluru",
    lat: 30,
    lng: 65,
    category: "Health & Fitness",
    matchLevel: "other",
    roi: "15–22%",
    established: "2017",
    units: 85,
    breakeven: "12–18 months",
    tags: ["Growing"],
    description:
      "Budget-friendly fitness franchise targeting tier-2 & tier-3 cities with micro-gym formats.",
  },
  {
    id: 7,
    name: "Bean & Leaf",
    logo: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=400&h=300",
    investment: "₹80K – ₹1.2 Lakh",
    location: "BTM Layout, Bengaluru",
    lat: 80,
    lng: 40,
    category: "Coffee & Cafe",
    matchLevel: "high",
    roi: "30–40%",
    established: "2020",
    units: 210,
    breakeven: "8–12 months",
    tags: ["Trending", "High ROI"],
    description:
      "Artisan specialty coffee brand with a cult-like following and Instagram-worthy store aesthetics.",
  },
  {
    id: 8,
    name: "PetCare Plus",
    logo: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=400&h=300",
    investment: "₹60K – ₹1 Lakh",
    location: "Electronic City, Bengaluru",
    lat: 85,
    lng: 60,
    category: "Pet Services",
    matchLevel: "other",
    roi: "25–32%",
    established: "2021",
    units: 48,
    breakeven: "10–14 months",
    tags: ["New", "Growing"],
    description:
      "Premium pet grooming & care franchise tapping into a rapidly expanding companion animal market.",
  },
  {
    id: 9,
    name: "BrightMinds Academy",
    logo: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=400&h=300",
    investment: "₹15L – ₹30 Lakh",
    location: "JP Nagar, Bengaluru",
    lat: 62,
    lng: 25,
    category: "Education",
    matchLevel: "high",
    roi: "20–30%",
    established: "2015",
    units: 480,
    breakeven: "16–22 months",
    tags: ["Premium", "Popular"],
    description:
      "K–12 enrichment centre franchise with STEM & coding curriculum and strong parent community trust.",
  },
  {
    id: 10,
    name: "GlowUp Studio",
    logo: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=400&h=300",
    investment: "₹10L – ₹20 Lakh",
    location: "MG Road, Bengaluru",
    lat: 45,
    lng: 50,
    category: "Beauty & Wellness",
    matchLevel: "selected",
    roi: "25–35%",
    established: "2018",
    units: 350,
    breakeven: "12–18 months",
    tags: ["Trending", "High ROI"],
    description:
      "Premium unisex beauty & wellness salon franchise with celebrity brand ambassadors and recurring revenue.",
  },
  {
    id: 11,
    name: "AutoShine Detailing",
    logo: "https://images.unsplash.com/photo-1507136566006-cfc505b114fc?auto=format&fit=crop&w=400&h=300",
    investment: "₹8L – ₹15 Lakh",
    location: "Hebbal, Bengaluru",
    lat: 18,
    lng: 55,
    category: "Automotive",
    matchLevel: "other",
    roi: "22–30%",
    established: "2020",
    units: 120,
    breakeven: "10–16 months",
    tags: ["New", "Growing"],
    description:
      "Premium car detailing & ceramic coating franchise with repeat customers and high-ticket services.",
  },
  {
    id: 12,
    name: "HomeServ Pro",
    logo: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=400&h=300",
    investment: "₹5L – ₹12 Lakh",
    location: "Bannerghatta Road, Bengaluru",
    lat: 75,
    lng: 70,
    category: "Home Services",
    matchLevel: "high",
    roi: "30–42%",
    established: "2019",
    units: 650,
    breakeven: "8–14 months",
    tags: ["High ROI", "Trending"],
    description:
      "On-demand home services aggregator franchise covering cleaning, plumbing, electrical & appliance repair.",
  },
  {
    id: 13,
    name: "KFC Express",
    logo: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=400&h=300",
    investment: "₹1.2 – ₹2.0 Cr",
    location: "Koramangala 5th Block, Bengaluru",
    lat: 52,
    lng: 48,
    category: "Food & Beverage",
    matchLevel: "selected",
    roi: "26–34%",
    established: "1952",
    units: 25000,
    breakeven: "20–30 months",
    tags: ["Top Rated", "Premium"],
    description:
      "World-renowned crispy chicken quick service restaurant franchise with high footfall formats.",
  },
  {
    id: 14,
    name: "Chai Point",
    logo: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&h=300",
    investment: "₹18 – ₹32 Lakh",
    location: "Bellandur Outer Ring Road, Bengaluru",
    lat: 48,
    lng: 68,
    category: "Coffee & Cafe",
    matchLevel: "high",
    roi: "32–40%",
    established: "2010",
    units: 280,
    breakeven: "10–15 months",
    tags: ["Indian Brand", "High ROI"],
    description:
      "India's largest organized chai retail chain with tech-enabled smart dispensers and IoT integration.",
  },
  {
    id: 15,
    name: "Cult.fit Studio",
    logo: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=400&h=300",
    investment: "₹45 – ₹80 Lakh",
    location: "Lavelle Road, Bengaluru",
    lat: 38,
    lng: 42,
    category: "Health & Fitness",
    matchLevel: "selected",
    roi: "28–36%",
    established: "2016",
    units: 600,
    breakeven: "14–20 months",
    tags: ["Trending", "Premium"],
    description:
      "Holistic wellness and group fitness studio franchise powered by celebrity trainers and an active app ecosystem.",
  },
  {
    id: 16,
    name: "Lenskart Optical",
    logo: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=400&h=300",
    investment: "₹30 – ₹55 Lakh",
    location: "Malleshwaram, Bengaluru",
    lat: 22,
    lng: 28,
    category: "Technology",
    matchLevel: "high",
    roi: "25–35%",
    established: "2010",
    units: 2000,
    breakeven: "12–18 months",
    tags: ["Popular", "High ROI"],
    description:
      "Omnichannel eyewear retail franchise with 3D virtual try-ons and robotic precision lens cutting.",
  },
  {
    id: 17,
    name: "Jawad Habib Hair & Beauty",
    logo: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=400&h=300",
    investment: "₹12 – ₹25 Lakh",
    location: "Sadashivanagar, Bengaluru",
    lat: 15,
    lng: 35,
    category: "Beauty & Wellness",
    matchLevel: "other",
    roi: "22–28%",
    established: "2006",
    units: 950,
    breakeven: "15–20 months",
    tags: ["Indian Brand"],
    description:
      "Household name salon & academy franchise offering master styling services and certified training courses.",
  },
  {
    id: 18,
    name: "Kidzee Preschool",
    logo: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=400&h=300",
    investment: "₹12 – ₹22 Lakh",
    location: "Sarjapur Road, Bengaluru",
    lat: 65,
    lng: 82,
    category: "Education",
    matchLevel: "high",
    roi: "24–32%",
    established: "2003",
    units: 2100,
    breakeven: "12–18 months",
    tags: ["Top Rated", "Popular"],
    description:
      "Pioneer in early childhood care and education with proprietary curriculum and pan-India parent trust.",
  },
  {
    id: 19,
    name: "Starbucks Coffee",
    logo: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=400&h=300",
    investment: "₹2.0 – ₹3.5 Cr",
    location: "UB City, Vittal Mallya Road, Bengaluru",
    lat: 44,
    lng: 46,
    category: "Coffee & Cafe",
    matchLevel: "selected",
    roi: "20–28%",
    established: "1971",
    units: 36000,
    breakeven: "28–38 months",
    tags: ["Premium"],
    description:
      "Global premier roaster and retailer of specialty coffees with unmatched brand equity and premium customer experience.",
  },
  {
    id: 20,
    name: "SpeedyWheels EV Hub",
    logo: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&h=300",
    investment: "₹15 – ₹28 Lakh",
    location: "Peenya Industrial Area, Bengaluru",
    lat: 12,
    lng: 18,
    category: "Automotive",
    matchLevel: "high",
    roi: "35–48%",
    established: "2022",
    units: 75,
    breakeven: "8–12 months",
    tags: ["New", "High ROI", "Trending"],
    description:
      "Next-generation EV battery swapping and two-wheeler servicing franchise riding the green mobility revolution.",
  },
  {
    id: 21,
    name: "Bark & Purr Lounge",
    logo: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=400&h=300",
    investment: "₹14 – ₹24 Lakh",
    location: "Kalyan Nagar, Bengaluru",
    lat: 28,
    lng: 72,
    category: "Pet Services",
    matchLevel: "other",
    roi: "26–34%",
    established: "2021",
    units: 32,
    breakeven: "10–15 months",
    tags: ["Growing"],
    description:
      "Boutique pet bakery, day care, and spa destination offering luxury pet parenting experiences.",
  },
  {
    id: 22,
    name: "Urban Clean Solutions",
    logo: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=400&h=300",
    investment: "₹8 – ₹16 Lakh",
    location: "Rajajinagar, Bengaluru",
    lat: 32,
    lng: 22,
    category: "Home Services",
    matchLevel: "high",
    roi: "32–44%",
    established: "2020",
    units: 140,
    breakeven: "7–11 months",
    tags: ["High ROI"],
    description:
      "Deep commercial and residential sanitation franchise with automated booking software and trained field teams.",
  },
  {
    id: 23,
    name: "Chai Sutta Bar",
    logo: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=400&h=300",
    investment: "₹16 – ₹25 Lakh",
    location: "Marathahalli Bridge, Bengaluru",
    lat: 56,
    lng: 78,
    category: "Coffee & Cafe",
    matchLevel: "high",
    roi: "38–52%",
    established: "2016",
    units: 450,
    breakeven: "6–9 months",
    tags: ["Indian Brand", "High ROI", "Trending"],
    description:
      "High-energy kulhad chai franchise with youth-centric vibes and explosive customer turnover.",
  },
  {
    id: 24,
    name: "Anytime Fitness",
    logo: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=400&h=300",
    investment: "₹1.0 – ₹1.8 Cr",
    location: "Koramangala 4th Block, Bengaluru",
    lat: 58,
    lng: 52,
    category: "Health & Fitness",
    matchLevel: "selected",
    roi: "22–30%",
    established: "2002",
    units: 5200,
    breakeven: "22–32 months",
    tags: ["Premium", "Top Rated"],
    description:
      "24/7 global gym franchise featuring keycard security, cloud-based member management, and world-class gear.",
  },
  {
    id: 25,
    name: "Coding Ninjas Junior",
    logo: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=400&h=300",
    investment: "₹10 – ₹20 Lakh",
    location: "Yelahanka New Town, Bengaluru",
    lat: 10,
    lng: 45,
    category: "Education",
    matchLevel: "high",
    roi: "28–38%",
    established: "2019",
    units: 160,
    breakeven: "9–14 months",
    tags: ["Trending", "High ROI"],
    description:
      "AI & robotics academy franchise preparing school students with practical programming skills and competitions.",
  },
  {
    id: 26,
    name: "Barbeque Nation",
    logo: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=400&h=300",
    investment: "₹2.2 – ₹3.8 Cr",
    location: "Indiranagar 100 Feet Rd, Bengaluru",
    lat: 26,
    lng: 38,
    category: "Food & Beverage",
    matchLevel: "selected",
    roi: "20–28%",
    established: "2006",
    units: 210,
    breakeven: "26–36 months",
    tags: ["Premium", "Popular"],
    description:
      "Live on-the-table grill buffet concept dining with massive group bookings and celebratory family traffic.",
  },
  {
    id: 27,
    name: "Dr. Fixit Home Solutions",
    logo: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=400&h=300",
    investment: "₹7 – ₹14 Lakh",
    location: "Bommanahalli, Bengaluru",
    lat: 78,
    lng: 62,
    category: "Home Services",
    matchLevel: "other",
    roi: "25–35%",
    established: "2001",
    units: 800,
    breakeven: "10–15 months",
    tags: ["Indian Brand"],
    description:
      "Waterproofing and structural repair franchise with Pidilite brand assurance and certified contractor networks.",
  },
  {
    id: 28,
    name: "Toni & Guy Salon",
    logo: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&h=300",
    investment: "₹40 – ₹70 Lakh",
    location: "Cunningham Road, Bengaluru",
    lat: 34,
    lng: 44,
    category: "Beauty & Wellness",
    matchLevel: "selected",
    roi: "24–32%",
    established: "1963",
    units: 480,
    breakeven: "16–24 months",
    tags: ["Premium", "Top Rated"],
    description:
      "Heritage British hairdressing salon franchise delivering catwalk-inspired styling and luxury haircare.",
  },
  {
    id: 29,
    name: "Xiaomi Mi Home",
    logo: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=400&h=300",
    investment: "₹25 – ₹45 Lakh",
    location: "Commercial Street, Bengaluru",
    lat: 36,
    lng: 54,
    category: "Technology",
    matchLevel: "high",
    roi: "28–36%",
    established: "2010",
    units: 3000,
    breakeven: "11–16 months",
    tags: ["Popular", "Trending"],
    description:
      "Smart home devices and smartphone flagship experiential retail franchise with high per-sqft sales velocity.",
  },
  {
    id: 30,
    name: "Bosch Car Service",
    logo: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=400&h=300",
    investment: "₹20 – ₹40 Lakh",
    location: "Hosur Road, Bengaluru",
    lat: 82,
    lng: 66,
    category: "Automotive",
    matchLevel: "selected",
    roi: "26–34%",
    established: "1921",
    units: 15000,
    breakeven: "14–20 months",
    tags: ["Top Rated", "Premium"],
    description:
      "Multi-brand independent workshop concept powered by genuine Bosch diagnostic software and parts.",
  },
  {
    id: 31,
    name: "The Belgian Waffle Co.",
    logo: "https://images.unsplash.com/photo-1568051243851-f9b136146e97?auto=format&fit=crop&w=400&h=300",
    investment: "₹14 – ₹22 Lakh",
    location: "Church Street, Bengaluru",
    lat: 42,
    lng: 48,
    category: "Food & Beverage",
    matchLevel: "high",
    roi: "35–48%",
    established: "2015",
    units: 420,
    breakeven: "8–12 months",
    tags: ["Trending", "High ROI"],
    description:
      "On-the-go specialty waffle sandwich brand with 200 sqft kiosk models and high gross margins.",
  },
  {
    id: 32,
    name: "PetVets Animal Clinic",
    logo: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=400&h=300",
    investment: "₹22 – ₹38 Lakh",
    location: "RMV 2nd Stage, Bengaluru",
    lat: 16,
    lng: 32,
    category: "Pet Services",
    matchLevel: "high",
    roi: "28–36%",
    established: "2018",
    units: 65,
    breakeven: "12–18 months",
    tags: ["Growing"],
    description:
      "Multi-specialty veterinary hospital franchise with in-house ultrasound, lab diagnostics, and pet surgery.",
  },
  {
    id: 33,
    name: "Gold's Gym",
    logo: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=400&h=300",
    investment: "₹1.5 – ₹3.0 Cr",
    location: "Whitefield Main Rd, Bengaluru",
    lat: 38,
    lng: 82,
    category: "Health & Fitness",
    matchLevel: "selected",
    roi: "20–28%",
    established: "1965",
    units: 700,
    breakeven: "24–36 months",
    tags: ["Top Rated", "Premium"],
    description:
      "The authority in bodybuilding and fitness conditioning with large-format centers and corporate wellness partnerships.",
  },
  {
    id: 34,
    name: "Kumon Learning Center",
    logo: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=400&h=300",
    investment: "₹8 – ₹15 Lakh",
    location: "Hennur Gardens, Bengaluru",
    lat: 20,
    lng: 65,
    category: "Education",
    matchLevel: "other",
    roi: "24–30%",
    established: "1958",
    units: 24000,
    breakeven: "10–15 months",
    tags: ["Popular"],
    description:
      "Individualized math & reading worksheets method building self-directed study habits across millions of students.",
  },
  {
    id: 35,
    name: "Mister Barber Gent's Salon",
    logo: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=400&h=300",
    investment: "₹9 – ₹18 Lakh",
    location: "Frazer Town, Bengaluru",
    lat: 30,
    lng: 50,
    category: "Beauty & Wellness",
    matchLevel: "high",
    roi: "30–42%",
    established: "2019",
    units: 180,
    breakeven: "9–13 months",
    tags: ["Trending", "High ROI"],
    description:
      "Modern vintage gentlemen's barbershop franchise with classic shave treatments and private beard styling.",
  },
  {
    id: 36,
    name: "CleanBreeze Laundry Hub",
    logo: "https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=400&h=300",
    investment: "₹10 – ₹19 Lakh",
    location: "Kudlu Gate, Bengaluru",
    lat: 72,
    lng: 58,
    category: "Home Services",
    matchLevel: "other",
    roi: "32–45%",
    established: "2021",
    units: 95,
    breakeven: "8–12 months",
    tags: ["New", "Growing", "High ROI"],
    description:
      "Automated express laundromat and steam pressing franchise with app notifications and doorstep pickup.",
  },
];
export const categoryMeta: Record<
  string,
  { icon: React.ElementType; bg: string; text: string; glow: string }
> = {
  "Food & Beverage": {
    icon: Utensils,
    bg: "bg-rose-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(244,63,94,0.4)]",
  },
  "Coffee & Cafe": {
    icon: Coffee,
    bg: "bg-emerald-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(16,185,129,0.4)]",
  },
  Technology: {
    icon: Smartphone,
    bg: "bg-blue-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(59,130,246,0.4)]",
  },
  "Health & Fitness": {
    icon: Dumbbell,
    bg: "bg-cyan-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(6,182,212,0.4)]",
  },
  "Pet Services": {
    icon: PawPrint,
    bg: "bg-orange-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(249,115,22,0.4)]",
  },
  Education: {
    icon: GraduationCap,
    bg: "bg-indigo-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(99,102,241,0.4)]",
  },
  "Beauty & Wellness": {
    icon: Scissors,
    bg: "bg-pink-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(236,72,153,0.4)]",
  },
  Automotive: {
    icon: Car,
    bg: "bg-sky-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(14,165,233,0.4)]",
  },
  "Home Services": {
    icon: Wrench,
    bg: "bg-teal-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(20,184,166,0.4)]",
  },
};
export const defaultMeta = {
  icon: Store,
  bg: "bg-[#d4af37]/10",
  text: "text-[#d4af37]",
  glow: "shadow-[0_0_15px_rgba(212,175,55,0.4)]",
};
export const getMeta = (cat: string) => categoryMeta[cat] || defaultMeta;
export const tagColors: Record<string, string> = {
  "Top Rated":
    "bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/20",
  Trending:
    "bg-rose-500/15 text-rose-600 dark:text-rose-400 border-rose-500/20",
  Premium:
    "bg-violet-500/15 text-violet-600 dark:text-violet-400 border-violet-500/20",
  Popular: "bg-sky-500/15 text-sky-600 dark:text-sky-400 border-sky-500/20",
  "Indian Brand":
    "bg-orange-500/15 text-orange-600 dark:text-orange-400 border-orange-500/20",
  New: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
  "High ROI":
    "bg-teal-500/15 text-teal-600 dark:text-teal-400 border-teal-500/20",
  Growing: "bg-blue-500/15 text-blue-600 dark:text-blue-400 border-blue-500/20",
};
