export interface Franchise {
  id: number;
  name: string;
  logo: string;
  investment: string;
  location: string;
  lat: number;
  lng: number;
  category: string;
  matchLevel: 'selected' | 'high' | 'other';
  roi: string;
  established: string;
  units: number;
  breakeven: string;
  tags: string[];
  description: string;
}

export const categories = [
  'All',
  'Food & Beverage',
  'Coffee & Cafe',
  'Technology',
  'Health & Fitness',
  'Pet Services',
  'Education',
  'Beauty & Wellness',
  'Automotive',
  'Home Services',
] as const;

export const franchises: Franchise[] = [
  {
    id: 1,
    name: "Domino's Pizza",
    logo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&h=300',
    investment: '₹35L – ₹60 Lakh',
    location: 'Koramangala, Bengaluru',
    lat: 55,
    lng: 45,
    category: 'Food & Beverage',
    matchLevel: 'selected',
    roi: '28–35%',
    established: '1960',
    units: 1920,
    breakeven: '14–18 months',
    tags: ['Top Rated', 'Trending'],
    description: "World's leading pizza delivery franchise with proven unit economics and 60+ years of global brand trust.",
  },
  {
    id: 2,
    name: "McDonald's",
    logo: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=400&h=300',
    investment: '₹1.5 – ₹2.5 Cr',
    location: 'Indiranagar, Bengaluru',
    lat: 25,
    lng: 30,
    category: 'Food & Beverage',
    matchLevel: 'high',
    roi: '22–30%',
    established: '1955',
    units: 40000,
    breakeven: '24–36 months',
    tags: ['Premium'],
    description: 'Iconic global QSR brand with massive brand recall, deep operational support, and a loyal customer base.',
  },
  {
    id: 3,
    name: 'Subway',
    logo: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=400&h=300',
    investment: '₹25 – ₹50 Lakh',
    location: 'HSR Layout, Bengaluru',
    lat: 70,
    lng: 55,
    category: 'Food & Beverage',
    matchLevel: 'high',
    roi: '20–28%',
    established: '1965',
    units: 37000,
    breakeven: '18–24 months',
    tags: ['Popular'],
    description: 'Health-conscious submarine sandwich franchise with flexible store formats and low operational overhead.',
  },
  {
    id: 4,
    name: 'Cafe Coffee Day',
    logo: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&h=300',
    investment: '₹20 – ₹40 Lakh',
    location: 'Jayanagar, Bengaluru',
    lat: 40,
    lng: 20,
    category: 'Coffee & Cafe',
    matchLevel: 'other',
    roi: '18–25%',
    established: '1996',
    units: 1750,
    breakeven: '20–28 months',
    tags: ['Indian Brand'],
    description: "India's favourite coffee chain with a strong loyalty base and pan-India brand recognition.",
  },
  {
    id: 5,
    name: 'TechFix Hub',
    logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=400&h=300',
    investment: '₹50K – ₹90K',
    location: 'Whitefield, Bengaluru',
    lat: 35,
    lng: 75,
    category: 'Technology',
    matchLevel: 'high',
    roi: '35–45%',
    established: '2019',
    units: 320,
    breakeven: '6–10 months',
    tags: ['New', 'High ROI'],
    description: 'Mobile & gadget repair franchise with low investment, high margins, and a booming after-market sector.',
  },
  {
    id: 6,
    name: 'FitLife Gyms',
    logo: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=400&h=300',
    investment: '₹2L – ₹5 Lakh',
    location: 'Marathahalli, Bengaluru',
    lat: 30,
    lng: 65,
    category: 'Health & Fitness',
    matchLevel: 'other',
    roi: '15–22%',
    established: '2017',
    units: 85,
    breakeven: '12–18 months',
    tags: ['Growing'],
    description: 'Budget-friendly fitness franchise targeting tier-2 & tier-3 cities with micro-gym formats.',
  },
  {
    id: 7,
    name: 'Bean & Leaf',
    logo: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=400&h=300',
    investment: '₹80K – ₹1.2 Lakh',
    location: 'BTM Layout, Bengaluru',
    lat: 80,
    lng: 40,
    category: 'Coffee & Cafe',
    matchLevel: 'high',
    roi: '30–40%',
    established: '2020',
    units: 210,
    breakeven: '8–12 months',
    tags: ['Trending', 'High ROI'],
    description: 'Artisan specialty coffee brand with a cult-like following and Instagram-worthy store aesthetics.',
  },
  {
    id: 8,
    name: 'PetCare Plus',
    logo: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=400&h=300',
    investment: '₹60K – ₹1 Lakh',
    location: 'Electronic City, Bengaluru',
    lat: 85,
    lng: 60,
    category: 'Pet Services',
    matchLevel: 'other',
    roi: '25–32%',
    established: '2021',
    units: 48,
    breakeven: '10–14 months',
    tags: ['New', 'Growing'],
    description: 'Premium pet grooming & care franchise tapping into a rapidly expanding companion animal market.',
  },
  {
    id: 9,
    name: 'BrightMinds Academy',
    logo: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=400&h=300',
    investment: '₹15L – ₹30 Lakh',
    location: 'JP Nagar, Bengaluru',
    lat: 62,
    lng: 25,
    category: 'Education',
    matchLevel: 'high',
    roi: '20–30%',
    established: '2015',
    units: 480,
    breakeven: '16–22 months',
    tags: ['Premium', 'Popular'],
    description: 'K–12 enrichment centre franchise with STEM & coding curriculum and strong parent community trust.',
  },
  {
    id: 10,
    name: 'GlowUp Studio',
    logo: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=400&h=300',
    investment: '₹10L – ₹20 Lakh',
    location: 'MG Road, Bengaluru',
    lat: 45,
    lng: 50,
    category: 'Beauty & Wellness',
    matchLevel: 'selected',
    roi: '25–35%',
    established: '2018',
    units: 350,
    breakeven: '12–18 months',
    tags: ['Trending', 'High ROI'],
    description: 'Premium unisex beauty & wellness salon franchise with celebrity brand ambassadors and recurring revenue.',
  },
  {
    id: 11,
    name: 'AutoShine Detailing',
    logo: 'https://images.unsplash.com/photo-1507136566006-cfc505b114fc?auto=format&fit=crop&w=400&h=300',
    investment: '₹8L – ₹15 Lakh',
    location: 'Hebbal, Bengaluru',
    lat: 18,
    lng: 55,
    category: 'Automotive',
    matchLevel: 'other',
    roi: '22–30%',
    established: '2020',
    units: 120,
    breakeven: '10–16 months',
    tags: ['New', 'Growing'],
    description: 'Premium car detailing & ceramic coating franchise with repeat customers and high-ticket services.',
  },
  {
    id: 12,
    name: 'HomeServ Pro',
    logo: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=400&h=300',
    investment: '₹5L – ₹12 Lakh',
    location: 'Bannerghatta Road, Bengaluru',
    lat: 75,
    lng: 70,
    category: 'Home Services',
    matchLevel: 'high',
    roi: '30–42%',
    established: '2019',
    units: 650,
    breakeven: '8–14 months',
    tags: ['High ROI', 'Trending'],
    description: 'On-demand home services aggregator franchise covering cleaning, plumbing, electrical & appliance repair.',
  },
];
