export interface Franchise {
  id: number;
  name: string;
  logo: string;
  investment: string;
  location: string;
  lat: number;
  lng: number;
  category: string;
  matchLevel: 'selected' | 'high' | 'other';
  rating: number;
  reviewCount: number;
  roi: string;
  established: string;
  tags: string[];
  description: string;
}

export const categories = [
  'All',
  'Food & Beverage',
  'Coffee & Cafe',
  'Technology',
  'Health & Fitness',
  'Pet Services',
] as const;

export const franchises: Franchise[] = [
  {
    id: 1,
    name: "Domino's Pizza",
    logo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&h=300',
    investment: '₹35L – ₹60 Lakh',
    location: 'Koramangala, Bengaluru',
    lat: 55,
    lng: 45,
    category: 'Food & Beverage',
    matchLevel: 'selected',
    rating: 4.8,
    reviewCount: 342,
    roi: '28–35%',
    established: '1960',
    tags: ['Top Rated', 'Trending'],
    description: 'World\'s leading pizza delivery franchise with proven unit economics.',
  },
  {
    id: 2,
    name: "McDonald's",
    logo: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=400&h=300',
    investment: '₹1.5 – ₹2.5 Cr',
    location: 'Indiranagar, Bengaluru',
    lat: 25,
    lng: 30,
    category: 'Food & Beverage',
    matchLevel: 'high',
    rating: 4.6,
    reviewCount: 528,
    roi: '22–30%',
    established: '1955',
    tags: ['Premium'],
    description: 'Iconic global QSR brand with massive brand recall and support.',
  },
  {
    id: 3,
    name: 'Subway',
    logo: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=400&h=300',
    investment: '₹25 – ₹50 Lakh',
    location: 'HSR Layout, Bengaluru',
    lat: 70,
    lng: 55,
    category: 'Food & Beverage',
    matchLevel: 'high',
    rating: 4.3,
    reviewCount: 215,
    roi: '20–28%',
    established: '1965',
    tags: ['Popular'],
    description: 'Health-conscious submarine sandwich franchise with flexible formats.',
  },
  {
    id: 4,
    name: 'Cafe Coffee Day',
    logo: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&h=300',
    investment: '₹20 – ₹40 Lakh',
    location: 'Jayanagar, Bengaluru',
    lat: 40,
    lng: 20,
    category: 'Coffee & Cafe',
    matchLevel: 'other',
    rating: 4.1,
    reviewCount: 189,
    roi: '18–25%',
    established: '1996',
    tags: ['Indian Brand'],
    description: 'India\'s favourite coffee chain with a strong loyalty base.',
  },
  {
    id: 5,
    name: 'TechFix Hub',
    logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=400&h=300',
    investment: '₹50K – ₹90K',
    location: 'Whitefield, Bengaluru',
    lat: 35,
    lng: 75,
    category: 'Technology',
    matchLevel: 'high',
    rating: 4.5,
    reviewCount: 97,
    roi: '35–45%',
    established: '2019',
    tags: ['New', 'High ROI'],
    description: 'Mobile & gadget repair franchise with low investment, high margins.',
  },
  {
    id: 6,
    name: 'FitLife Gyms',
    logo: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=400&h=300',
    investment: '₹2L – ₹5 Lakh',
    location: 'Marathahalli, Bengaluru',
    lat: 30,
    lng: 65,
    category: 'Health & Fitness',
    matchLevel: 'other',
    rating: 4.0,
    reviewCount: 64,
    roi: '15–22%',
    established: '2017',
    tags: ['Growing'],
    description: 'Budget-friendly fitness franchise targeting tier-2 & tier-3 cities.',
  },
  {
    id: 7,
    name: 'Bean & Leaf',
    logo: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=400&h=300',
    investment: '₹80K – ₹1.2 Lakh',
    location: 'BTM Layout, Bengaluru',
    lat: 80,
    lng: 40,
    category: 'Coffee & Cafe',
    matchLevel: 'high',
    rating: 4.7,
    reviewCount: 156,
    roi: '30–40%',
    established: '2020',
    tags: ['Trending', 'High ROI'],
    description: 'Artisan specialty coffee brand with a cult-like following.',
  },
  {
    id: 8,
    name: 'PetCare Plus',
    logo: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=400&h=300',
    investment: '₹60K – ₹1 Lakh',
    location: 'Electronic City, Bengaluru',
    lat: 85,
    lng: 60,
    category: 'Pet Services',
    matchLevel: 'other',
    rating: 4.4,
    reviewCount: 78,
    roi: '25–32%',
    established: '2021',
    tags: ['New', 'Growing'],
    description: 'Premium pet grooming & care franchise tapping into a booming market.',
  },
];
