import {
  Building2,
  Store,
  Warehouse,
  LayoutGrid,
  Users,
  Factory,
  LandPlot,
} from "lucide-react";

export interface Property {
  id: number;
  name: string;
  logo: string;
  price: string;
  location: string;
  lat: number;
  lng: number;
  category: string;
  matchLevel: "selected" | "high" | "other";
  area: string;
  builtYear: string;
  floors: number;
  furnishing: string;
  tags: string[];
  description: string;
}

export const categories = [
  "All",
  "Office Space",
  "Retail Shop",
  "Warehouse",
  "Showroom",
  "Co-working",
  "Industrial",
  "Plot / Land",
] as const;

export const properties: Property[] = [
  {
    id: 1,
    name: "Skyline Business Tower",
    logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&h=300",
    price: "₹1.2 Cr",
    location: "HITEC City, Hyderabad",
    lat: 55,
    lng: 45,
    category: "Office Space",
    matchLevel: "selected",
    area: "1,800 – 2,500 sq.ft",
    builtYear: "2022",
    floors: 12,
    furnishing: "Fully Furnished",
    tags: ["Premium", "Verified"],
    description:
      "Grade-A office space in the heart of HITEC City with panoramic views, 24/7 security, and modern amenities.",
  },
  {
    id: 2,
    name: "Metro Mall Retail Unit",
    logo: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=400&h=300",
    price: "₹85 Lakh",
    location: "Jubilee Hills, Hyderabad",
    lat: 25,
    lng: 30,
    category: "Retail Shop",
    matchLevel: "high",
    area: "450 – 700 sq.ft",
    builtYear: "2020",
    floors: 3,
    furnishing: "Semi Furnished",
    tags: ["Hot Deal"],
    description:
      "Prime retail space on the ground floor of a high-footfall mall near Jubilee Hills checkpost.",
  },
  {
    id: 3,
    name: "Greenfield Logistics Hub",
    logo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=400&h=300",
    price: "₹2.5 Cr",
    location: "Shamshabad, Hyderabad",
    lat: 70,
    lng: 55,
    category: "Warehouse",
    matchLevel: "high",
    area: "5,000 – 8,000 sq.ft",
    builtYear: "2021",
    floors: 1,
    furnishing: "Unfurnished",
    tags: ["New Listing"],
    description:
      "Large-scale warehouse with loading docks, 24ft clear height, and proximity to Rajiv Gandhi International Airport.",
  },
  {
    id: 4,
    name: "Crystal Auto Showroom",
    logo: "https://images.unsplash.com/photo-1567449303183-ae0d6ed1498e?auto=format&fit=crop&w=400&h=300",
    price: "₹3.8 Cr",
    location: "Banjara Hills, Hyderabad",
    lat: 40,
    lng: 20,
    category: "Showroom",
    matchLevel: "other",
    area: "3,200 – 4,000 sq.ft",
    builtYear: "2019",
    floors: 2,
    furnishing: "Shell & Core",
    tags: ["Premium"],
    description:
      "Double-height showroom space on Road No. 12 with massive glass frontage and dedicated parking.",
  },
  {
    id: 5,
    name: "WorkHub Flex Space",
    logo: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=400&h=300",
    price: "₹50 Lakh",
    location: "Gachibowli, Hyderabad",
    lat: 35,
    lng: 75,
    category: "Co-working",
    matchLevel: "high",
    area: "800 – 1,200 sq.ft",
    builtYear: "2023",
    floors: 8,
    furnishing: "Fully Furnished",
    tags: ["New Listing", "Ready to Move"],
    description:
      "Plug-and-play co-working space with high-speed internet, meeting rooms, and cafeteria access.",
  },
  {
    id: 6,
    name: "Vasavi Industrial Complex",
    logo: "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=400&h=300",
    price: "₹4.5 Cr",
    location: "Jeedimetla, Hyderabad",
    lat: 30,
    lng: 65,
    category: "Industrial",
    matchLevel: "other",
    area: "10,000 – 15,000 sq.ft",
    builtYear: "2018",
    floors: 2,
    furnishing: "Unfurnished",
    tags: ["Verified"],
    description:
      "Industrial shed with heavy power supply, water treatment plant, and easy access to NH-44.",
  },
  {
    id: 7,
    name: "Prestige Office Suites",
    logo: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=400&h=300",
    price: "₹65 Lakh",
    location: "Madhapur, Hyderabad",
    lat: 80,
    lng: 40,
    category: "Office Space",
    matchLevel: "high",
    area: "600 – 900 sq.ft",
    builtYear: "2023",
    floors: 6,
    furnishing: "Fully Furnished",
    tags: ["Ready to Move", "High ROI"],
    description:
      "Boutique office suites with private cabins, pantry, and dedicated parking in the IT corridor.",
  },
  {
    id: 8,
    name: "Sunshine Commercial Plot",
    logo: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=400&h=300",
    price: "₹1.8 Cr",
    location: "Kompally, Hyderabad",
    lat: 85,
    lng: 60,
    category: "Plot / Land",
    matchLevel: "other",
    area: "2,400 sq.yards",
    builtYear: "N/A",
    floors: 0,
    furnishing: "N/A",
    tags: ["Verified", "High ROI"],
    description:
      "HMDA-approved commercial plot on a 100ft road with clear title and excellent connectivity.",
  },
  {
    id: 9,
    name: "Meridian Retail Plaza",
    logo: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=400&h=300",
    price: "₹1.5 Cr",
    location: "Kukatpally, Hyderabad",
    lat: 62,
    lng: 25,
    category: "Retail Shop",
    matchLevel: "high",
    area: "1,000 – 1,500 sq.ft",
    builtYear: "2021",
    floors: 4,
    furnishing: "Semi Furnished",
    tags: ["Hot Deal", "Verified"],
    description:
      "Corner retail unit in a bustling commercial complex near KPHB metro station.",
  },
  {
    id: 10,
    name: "Pinnacle Business Park",
    logo: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=400&h=300",
    price: "₹95 Lakh",
    location: "Financial District, Hyderabad",
    lat: 45,
    lng: 50,
    category: "Office Space",
    matchLevel: "selected",
    area: "1,200 – 1,800 sq.ft",
    builtYear: "2022",
    floors: 15,
    furnishing: "Warm Shell",
    tags: ["Premium", "New Listing"],
    description:
      "Premium office space in the Financial District with LEED-certified green building standards.",
  },
  {
    id: 11,
    name: "Lakshmi Warehouse Park",
    logo: "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=400&h=300",
    price: "₹3.2 Cr",
    location: "Patancheru, Hyderabad",
    lat: 18,
    lng: 55,
    category: "Warehouse",
    matchLevel: "other",
    area: "8,000 – 12,000 sq.ft",
    builtYear: "2020",
    floors: 1,
    furnishing: "Unfurnished",
    tags: ["Verified"],
    description:
      "Cold-storage capable warehouse with 3-phase power, fire safety systems, and round-the-clock security.",
  },
  {
    id: 12,
    name: "Horizon Co-work Hub",
    logo: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=400&h=300",
    price: "₹40 Lakh",
    location: "Kondapur, Hyderabad",
    lat: 75,
    lng: 70,
    category: "Co-working",
    matchLevel: "high",
    area: "500 – 800 sq.ft",
    builtYear: "2024",
    floors: 5,
    furnishing: "Fully Furnished",
    tags: ["New Listing", "Ready to Move"],
    description:
      "Modern co-working space with ergonomic furniture, video conferencing rooms, and community events.",
  },
  {
    id: 13,
    name: "One BKC Tower Corporate Suites",
    logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&h=300",
    price: "₹8.5 Cr",
    location: "Bandra Kurla Complex, Mumbai",
    lat: 42,
    lng: 35,
    category: "Office Space",
    matchLevel: "selected",
    area: "4,200 sq.ft",
    builtYear: "2022",
    floors: 18,
    furnishing: "Warm Shell",
    tags: ["Premium", "Verified"],
    description:
      "Grade-A LEED Platinum certified corporate office floor with double-glazed acoustic facade and 100% DG backup.",
  },
  {
    id: 14,
    name: "CyberPark Tech Center",
    logo: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=400&h=300",
    price: "₹3.2 Cr",
    location: "HITEC City, Hyderabad",
    lat: 48,
    lng: 65,
    category: "Office Space",
    matchLevel: "high",
    area: "2,800 sq.ft",
    builtYear: "2023",
    floors: 12,
    furnishing: "Fully Furnished",
    tags: ["Ready to Move", "High ROI"],
    description:
      "Turnkey IT office suite with 65 workstations, 3 executive cabins, conference room, and cafeteria.",
  },
  {
    id: 15,
    name: "Phoenix Market Galleria Retail",
    logo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=400&h=300",
    price: "₹2.8 Cr",
    location: "Viman Nagar, Pune",
    lat: 52,
    lng: 45,
    category: "Retail Shop",
    matchLevel: "selected",
    area: "1,450 sq.ft",
    builtYear: "2021",
    floors: 3,
    furnishing: "Bare Shell",
    tags: ["Hot Deal", "Premium"],
    description:
      "Corner retail anchor showroom with 35 ft main boulevard frontage directly opposite high-density cinema multiplex.",
  },
  {
    id: 16,
    name: "Logistics Hub 24",
    logo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=400&h=300",
    price: "₹5.6 Cr",
    location: "Bhiwandi Expressway, Mumbai",
    lat: 25,
    lng: 28,
    category: "Warehouse",
    matchLevel: "high",
    area: "28,000 sq.ft",
    builtYear: "2023",
    floors: 1,
    furnishing: "Unfurnished",
    tags: ["Verified", "Ready to Move"],
    description:
      "PEB industrial warehouse with 12m clear height, 6 automated hydraulic dock levelers, and FM2 flooring.",
  },
  {
    id: 17,
    name: "Prestige Prime Commercial Plot",
    logo: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=400&h=300",
    price: "₹6.4 Cr",
    location: "Devanahalli Airport Corridor, Bengaluru",
    lat: 14,
    lng: 52,
    category: "Plot / Land",
    matchLevel: "selected",
    area: "18,000 sq.ft",
    builtYear: "2024",
    floors: 0,
    furnishing: "Unfurnished",
    tags: ["High ROI", "New Listing"],
    description:
      "Freehold clear title commercial corner plot on 120ft main arterial road with 3.25 FSI approval for IT towers.",
  },
  {
    id: 18,
    name: "Autobahn Luxury Showroom",
    logo: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=400&h=300",
    price: "₹7.2 Cr",
    location: "Golf Course Road, Gurugram",
    lat: 30,
    lng: 48,
    category: "Showroom",
    matchLevel: "selected",
    area: "6,500 sq.ft",
    builtYear: "2022",
    floors: 2,
    furnishing: "Semi-Furnished",
    tags: ["Premium", "Verified"],
    description:
      "Ultra-luxury double-height glass showroom ideal for premium automotive or luxury interior brands with 15 dedicated parking bays.",
  },
  {
    id: 19,
    name: "WeWork Smart Campus",
    logo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=400&h=300",
    price: "₹1.4 Cr",
    location: "Indiranagar 100ft Rd, Bengaluru",
    lat: 36,
    lng: 42,
    category: "Co-working",
    matchLevel: "high",
    area: "1,900 sq.ft",
    builtYear: "2023",
    floors: 4,
    furnishing: "Fully Furnished",
    tags: ["Ready to Move", "High ROI"],
    description:
      "Plug & play collaborative workspace with acoustic phone booths, podcast studio, barista bar, and high-speed fiber.",
  },
  {
    id: 20,
    name: "Automotive Ancillary Industrial Shed",
    logo: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=400&h=300",
    price: "₹3.8 Cr",
    location: "Chakan Industrial Zone, Pune",
    lat: 68,
    lng: 32,
    category: "Industrial",
    matchLevel: "other",
    area: "15,000 sq.ft",
    builtYear: "2020",
    floors: 1,
    furnishing: "Unfurnished",
    tags: ["Verified", "Ready to Move"],
    description:
      "Heavy engineering industrial plant with 10-tonne overhead gantry crane, 250 KVA sanctioned power, and fire NOC.",
  },
  {
    id: 21,
    name: "DLF CyberCity Executive Floor",
    logo: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=400&h=300",
    price: "₹11.2 Cr",
    location: "Cyber City Phase II, Gurugram",
    lat: 28,
    lng: 58,
    category: "Office Space",
    matchLevel: "selected",
    area: "6,800 sq.ft",
    builtYear: "2023",
    floors: 24,
    furnishing: "Warm Shell",
    tags: ["Premium", "Verified"],
    description:
      "Prestigious corporate headquarters floor with panoramic city views, direct metro skywalk connectivity, and multi-tier security.",
  },
  {
    id: 22,
    name: "Connaught Promenade Boutique Shop",
    logo: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=400&h=300",
    price: "₹4.5 Cr",
    location: "Inner Circle, Connaught Place, New Delhi",
    lat: 20,
    lng: 60,
    category: "Retail Shop",
    matchLevel: "selected",
    area: "1,100 sq.ft",
    builtYear: "2019",
    floors: 2,
    furnishing: "Fully Furnished",
    tags: ["Hot Deal", "Top Rated"],
    description:
      "Heritage arcade retail shop with heavy luxury footfall, split air-conditioning, mezzanine office, and display windows.",
  },
  {
    id: 23,
    name: "Kalyani Tech Logistics Park",
    logo: "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=400&h=300",
    price: "₹8.9 Cr",
    location: "Oragadam Industrial Corridor, Chennai",
    lat: 80,
    lng: 50,
    category: "Warehouse",
    matchLevel: "high",
    area: "42,000 sq.ft",
    builtYear: "2024",
    floors: 1,
    furnishing: "Unfurnished",
    tags: ["New Listing", "Verified"],
    description:
      "Modern multi-client fulfilment center with ESFR sprinkler systems, 14 dock bays, and expansive trailer staging area.",
  },
  {
    id: 24,
    name: "Mindspace Innovation Workspace",
    logo: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&h=300",
    price: "₹1.9 Cr",
    location: "Madhapur, Hyderabad",
    lat: 50,
    lng: 72,
    category: "Co-working",
    matchLevel: "high",
    area: "2,400 sq.ft",
    builtYear: "2023",
    floors: 7,
    furnishing: "Fully Furnished",
    tags: ["Ready to Move", "Trending"],
    description:
      "Designer enterprise co-working facility with dedicated team suites, wellness zones, meeting pods, and biometric access.",
  },
  {
    id: 25,
    name: "Hennur Expressway Mixed-Use Land",
    logo: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=400&h=300",
    price: "₹4.8 Cr",
    location: "Hennur Main Road, Bengaluru",
    lat: 18,
    lng: 68,
    category: "Plot / Land",
    matchLevel: "other",
    area: "12,500 sq.ft",
    builtYear: "2024",
    floors: 0,
    furnishing: "Unfurnished",
    tags: ["High ROI", "New Listing"],
    description:
      "BDA approved commercial conversion plot with 90ft road frontage in a rapidly growing high-income residential catchment.",
  },
  {
    id: 26,
    name: "Nexus Koramangala Flagship Showroom",
    logo: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=400&h=300",
    price: "₹5.1 Cr",
    location: "Koramangala 80ft Road, Bengaluru",
    lat: 54,
    lng: 50,
    category: "Showroom",
    matchLevel: "selected",
    area: "3,800 sq.ft",
    builtYear: "2022",
    floors: 2,
    furnishing: "Semi-Furnished",
    tags: ["Premium", "Hot Deal"],
    description:
      "High-visibility corner commercial showroom with glass facade, dedicated customer lift, and rooftop lounge potential.",
  },
  {
    id: 27,
    name: "Jigani Engineering Fabrication Plant",
    logo: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=400&h=300",
    price: "₹2.9 Cr",
    location: "Jigani Industrial Area Phase 1, Bengaluru",
    lat: 84,
    lng: 62,
    category: "Industrial",
    matchLevel: "other",
    area: "9,500 sq.ft",
    builtYear: "2021",
    floors: 1,
    furnishing: "Unfurnished",
    tags: ["Verified", "Ready to Move"],
    description:
      "Approved industrial factory unit with heavy load RCC flooring, industrial water line, and transformer yard.",
  },
  {
    id: 28,
    name: "Brigade Gateway Office Suite",
    logo: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=400&h=300",
    price: "₹4.1 Cr",
    location: "Rajajinagar, Bengaluru",
    lat: 34,
    lng: 26,
    category: "Office Space",
    matchLevel: "high",
    area: "3,100 sq.ft",
    builtYear: "2022",
    floors: 16,
    furnishing: "Fully Furnished",
    tags: ["Verified", "Ready to Move"],
    description:
      "Integrated lifestyle complex office suite with direct bridge to World Trade Center and five-star hotel amenities.",
  },
  {
    id: 29,
    name: "South Extension High Street Retail",
    logo: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=400&h=300",
    price: "₹3.9 Cr",
    location: "South Extension Part II, New Delhi",
    lat: 24,
    lng: 62,
    category: "Retail Shop",
    matchLevel: "high",
    area: "980 sq.ft",
    builtYear: "2020",
    floors: 2,
    furnishing: "Fully Furnished",
    tags: ["Hot Deal", "Popular"],
    description:
      "Prime fashion high street storefront with high purchasing power pedestrian traffic and verified rental yield.",
  },
  {
    id: 30,
    name: "Taloja Cold Storage Facility",
    logo: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=400&h=300",
    price: "₹7.8 Cr",
    location: "MIDC Taloja, Navi Mumbai",
    lat: 62,
    lng: 28,
    category: "Warehouse",
    matchLevel: "selected",
    area: "32,000 sq.ft",
    builtYear: "2023",
    floors: 1,
    furnishing: "Semi-Furnished",
    tags: ["Premium", "Verified"],
    description:
      "Multi-temperature cold chain facility (-25°C to +4°C) with ammonia refrigeration plant and sealed dock tunnels.",
  },
  {
    id: 31,
    name: "Whitefield Tech Boulevard Plot",
    logo: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=400&h=300",
    price: "₹9.2 Cr",
    location: "EPIP Zone, Whitefield, Bengaluru",
    lat: 38,
    lng: 85,
    category: "Plot / Land",
    matchLevel: "selected",
    area: "24,000 sq.ft",
    builtYear: "2024",
    floors: 0,
    furnishing: "Unfurnished",
    tags: ["High ROI", "Verified"],
    description:
      "KIADB sanctioned IT/ITES industrial corner plot with 150ft dual road access and direct metro line walking distance.",
  },
  {
    id: 32,
    name: "Indore Super Corridor Tech Showroom",
    logo: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=400&h=300",
    price: "₹2.2 Cr",
    location: "Super Corridor, Indore",
    lat: 66,
    lng: 44,
    category: "Showroom",
    matchLevel: "other",
    area: "2,600 sq.ft",
    builtYear: "2023",
    floors: 2,
    furnishing: "Bare Shell",
    tags: ["New Listing", "High ROI"],
    description:
      "Fast appreciating commercial showroom on 8-lane expressway connecting upcoming tech parks and residential townships.",
  },
  {
    id: 33,
    name: "Awfis Smart Shared Workspace",
    logo: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=400&h=300",
    price: "₹1.1 Cr",
    location: "MG Road Metro Station, Bengaluru",
    lat: 42,
    lng: 52,
    category: "Co-working",
    matchLevel: "high",
    area: "1,500 sq.ft",
    builtYear: "2023",
    floors: 3,
    furnishing: "Fully Furnished",
    tags: ["Ready to Move", "Popular"],
    description:
      "Central business district flexible office space with enterprise internet, boardroom credits, and visitor lounge.",
  },
  {
    id: 34,
    name: "Sriperumbudur Electronics SMT Facility",
    logo: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=400&h=300",
    price: "₹6.1 Cr",
    location: "SIPCOT Industrial Complex, Sriperumbudur",
    lat: 78,
    lng: 45,
    category: "Industrial",
    matchLevel: "selected",
    area: "22,000 sq.ft",
    builtYear: "2022",
    floors: 1,
    furnishing: "Semi-Furnished",
    tags: ["Premium", "Verified"],
    description:
      "Cleanroom Class 10,000 electronics assembly plant with static-dissipative ESD flooring and precision HVAC chillers.",
  },
  {
    id: 35,
    name: "EBD Sector 65 SCO Commercial Plots",
    logo: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=400&h=300",
    price: "₹7.5 Cr",
    location: "Golf Course Extension Rd, Gurugram",
    lat: 32,
    lng: 62,
    category: "Plot / Land",
    matchLevel: "selected",
    area: "1,650 sq.ft",
    builtYear: "2024",
    floors: 4,
    furnishing: "Unfurnished",
    tags: ["Hot Deal", "High ROI"],
    description:
      "Shop-cum-office (SCO) plot with B+G+4 floors development rights and open-air plaza dining concept.",
  },
  {
    id: 36,
    name: "Godrej Two Commercial Hub",
    logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&h=300",
    price: "₹9.8 Cr",
    location: "Vikhroli East, Mumbai",
    lat: 46,
    lng: 32,
    category: "Office Space",
    matchLevel: "selected",
    area: "5,400 sq.ft",
    builtYear: "2023",
    floors: 22,
    furnishing: "Warm Shell",
    tags: ["Premium", "Top Rated"],
    description:
      "Ultra-efficient column-free office floor plates with green mangrove views, campus food court, and creche facilities.",
  },
];

export const categoryMeta: Record<
  string,
  { icon: React.ElementType; bg: string; text: string; glow: string }
> = {
  "Office Space": {
    icon: Building2,
    bg: "bg-blue-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(59,130,246,0.4)]",
  },
  "Retail Shop": {
    icon: Store,
    bg: "bg-rose-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(244,63,94,0.4)]",
  },
  Warehouse: {
    icon: Warehouse,
    bg: "bg-amber-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(245,158,11,0.4)]",
  },
  Showroom: {
    icon: LayoutGrid,
    bg: "bg-violet-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(139,92,246,0.4)]",
  },
  "Co-working": {
    icon: Users,
    bg: "bg-emerald-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(16,185,129,0.4)]",
  },
  Industrial: {
    icon: Factory,
    bg: "bg-cyan-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(6,182,212,0.4)]",
  },
  "Plot / Land": {
    icon: LandPlot,
    bg: "bg-teal-500",
    text: "text-white",
    glow: "shadow-[0_0_20px_rgba(20,184,166,0.4)]",
  },
};

export const defaultMeta = {
  icon: Building2,
  bg: "bg-[#d4af37]/10",
  text: "text-[#d4af37]",
  glow: "shadow-[0_0_15px_rgba(212,175,55,0.4)]",
};

export const getMeta = (cat: string) => categoryMeta[cat] || defaultMeta;

export const tagColors: Record<string, string> = {
  Premium:
    "bg-violet-500/15 text-violet-600 dark:text-violet-400 border-violet-500/20",
  Verified:
    "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
  "Hot Deal":
    "bg-rose-500/15 text-rose-600 dark:text-rose-400 border-rose-500/20",
  "New Listing":
    "bg-sky-500/15 text-sky-600 dark:text-sky-400 border-sky-500/20",
  "Ready to Move":
    "bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/20",
  "Under Construction":
    "bg-orange-500/15 text-orange-600 dark:text-orange-400 border-orange-500/20",
  "High ROI":
    "bg-teal-500/15 text-teal-600 dark:text-teal-400 border-teal-500/20",
};
