import { Store, MapPin, Clock, TrendingDown, Calendar, Users } from "lucide-react";

export const numbersSpeakData = {
  sectionLabel: "NUMBERS SECTION",
  title: "Numbers that speak for themselves",
  subtitle:
    "Verified data from 187 outlet outlets — FY 2023–24 annual report.",
  verifiedLabel: "Linkedin",
  stats: [
    {
      icon: Store,
      value: "187",
      suffix: "+",
      label: "Active Outlets",
      sublabel: "Nationwide",
      intent: "warning",
      animateType: "counter" as const,
    },
    {
      icon: MapPin,
      value: "14",
      suffix: "",
      label: "Cities Covered",
      sublabel: "Tier 1, Tier 2 Cities",
      intent: "success",
      animateType: "counter" as const,
    },
    {
      icon: Clock,
      value: "8",
      suffix: "",
      label: "Years in Business",
      sublabel: "Since 2016",
      intent: "info",
      animateType: "counter" as const,
    },
    {
      icon: TrendingDown,
      value: "31",
      suffix: "%",
      label: "Average ROI",
      sublabel: "Across all models",
      intent: "warning",
      animateType: "percentage" as const,
    },
    {
      icon: Calendar,
      value: "21",
      suffix: " mo.",
      label: "Avg. Payback",
      sublabel: "Average across all FOCO",
      intent: "success",
      animateType: "counter" as const,
    },
    {
      icon: Users,
      value: "94",
      suffix: "%",
      label: "Partner Satisfaction",
      sublabel: "Based on NPS survey",
      intent: "info",
      animateType: "percentage" as const,
    },
  ],
};
