import {
  FileText,
  Building,
  TrendingUp,
  Calendar,
  Tag,
  Users,
  Store,
  CheckCircle2,
  Maximize,
  BarChart2,
  Clock,
  Briefcase,
  Layers,
  Percent,
} from "lucide-react";

export const commercialData = {
  tabs: ["Full Lease", "Sub Lease", "Outright Sale", "Pre-Leased", "Fractional"],
  tabData: {
    "Full Lease": {
      title: "Full Building / Wing Lease",
      headerIcon: Tag,
      headerIconBg: "bg-indigo-500",
      primaryAmountLabel: "MONTHLY LEASE / RENT",
      primaryAmount: "₹1.20L – ₹14.5L",
      primaryAmountColor: "text-[#0a1128] dark:text-white",
      primaryDesc: "/mo",
      primarySub: "₹95/sq.ft · Full Lease",
      secondaryBadge: {
        text: "Direct Master Lease",
        color:
          "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-400 dark:border-emerald-700/50",
      },
      secondaryDarkCard: {
        label: "ADVANCE DEPOSIT",
        value: "6 Months",
        desc: "Refundable deposit",
      },
      details: [
        {
          label: "Full Lease / Sub Lease",
          value: "Full Master Lease",
          icon: FileText,
          bgClass: "bg-gradient-to-br from-[#10B981] to-[#047857]",
        },
        {
          label: "Maintenance Charges",
          value: "₹12/sq.ft / mo",
          icon: Building,
          bgClass: "bg-gradient-to-br from-[#3B82F6] to-[#1D4ED8]",
        },
        {
          label: "Rent Escalation",
          value: "5% p.a.",
          icon: TrendingUp,
          bgClass: "bg-gradient-to-br from-[#F97316] to-[#C2410C]",
        },
        {
          label: "Escalation Every",
          value: "36 Months (3 Yrs)",
          icon: Calendar,
          bgClass: "bg-gradient-to-br from-[#8B5CF6] to-[#6D28D9]",
        },

        {
          label: "Units Available",
          value: "4 Floors / Full Bldg",
          icon: Layers,
          bgClass: "bg-gradient-to-br from-[#14B8A6] to-[#0F766E]",
        },
        {
          label: "Minimum Sq Ft",
          value: "1,200 sq.ft min.",
          icon: Maximize,
          bgClass: "bg-gradient-to-br from-[#bf953f] to-[#b38728]",
        },
        {
          label: "Additional Charges",
          value: "CAM + Electricity extra",
          icon: Percent,
          bgClass: "bg-gradient-to-br from-[#F43F5E] to-[#BE123C]",
        },
      ],
      footer: {
        type: "split",
        left: "Remarks",
        right: "Grade A asset with 100% power backup & OC received",
      },
    },
    "Sub Lease": {
      title: "Sub Lease Specifications",
      headerIcon: Briefcase,
      headerIconBg: "bg-blue-500",
      primaryAmountLabel: "SUB LEASE MONTHLY RENT",
      primaryAmount: "₹85,000",
      primaryAmountColor: "text-[#0a1128] dark:text-white",
      primaryDesc: "/mo",
      primarySub: "₹85/sq.ft · Flexible Sublease",
      secondaryBadge: {
        text: "Sub Lease Permitted",
        color:
          "bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-700/50",
      },
      secondaryDarkCard: {
        label: "ADVANCE DEPOSIT",
        value: "3 Months",
        desc: "Low lock-in capital",
      },
      details: [
        {
          label: "Lease Model",
          value: "Sub Lease Permitted",
          icon: FileText,
          bgClass: "bg-gradient-to-br from-[#3B82F6] to-[#1D4ED8]",
        },
        {
          label: "Unit No (If any)",
          value: "Unit 302, 3rd Floor",
          icon: Layers,
          bgClass: "bg-gradient-to-br from-[#8B5CF6] to-[#6D28D9]",
        },
        {
          label: "Remaining Tenure",
          value: "38 Months remaining",
          icon: Calendar,
          bgClass: "bg-gradient-to-br from-[#0EA5E9] to-[#0369A1]",
        },
        {
          label: "Existing Lease Tenure",
          value: "5 Years (Active)",
          icon: Clock,
          bgClass: "bg-gradient-to-br from-[#10B981] to-[#047857]",
        },
        {
          label: "Maintenance Charges",
          value: "₹10/sq.ft included",
          icon: Building,
          bgClass: "bg-gradient-to-br from-[#F97316] to-[#C2410C]",
        },
        {
          label: "Tentative Month",
          value: "Available Next Month",
          icon: CheckCircle2,
          bgClass: "bg-gradient-to-br from-[#14B8A6] to-[#0F766E]",
        },
        {
          label: "Existing Tenant (Industry)",
          value: "Fintech / IT Services",
          icon: Users,
          bgClass: "bg-gradient-to-br from-[#bf953f] to-[#b38728]",
        },
        {
          label: "Remarks",
          value: "Landlord NOC pre-approved",
          icon: Tag,
          bgClass: "bg-gradient-to-br from-[#F43F5E] to-[#BE123C]",
        },
      ],
      footer: {
        type: "split",
        left: "Sub Lease Terms",
        right: "Plug & Play ready with workstations and furniture included",
      },
    },
    "Outright Sale": {
      title: "Asset Sale & Pricing",
      headerIcon: Tag,
      headerIconBg: "bg-red-500",
      primaryAmountLabel: "BOX PRICE / TOTAL ASSET",
      primaryAmount: "₹18.50 Cr",
      primaryAmountColor: "text-[#0a1128] dark:text-white",
      primaryDesc: "",
      primarySub: "₹14,500 / sq.ft (Built-Up)",
      secondaryBadge: {
        text: "Freehold Asset",
        color:
          "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-900/30 dark:text-amber-500 dark:border-amber-700/50",
      },
      secondaryDarkCard: {
        label: "EST. RENTAL YIELD",
        value: "8.4% pa",
        desc: "High ROI Potential",
      },
      details: [
        {
          label: "Sale Type",
          value: "Full Asset Outright",
          icon: Tag,
          bgClass: "bg-gradient-to-br from-[#10B981] to-[#047857]",
        },
        {
          label: "Per Sq Ft / Yard",
          value: "₹14,500/sq.ft",
          icon: Maximize,
          bgClass: "bg-gradient-to-br from-[#3B82F6] to-[#1D4ED8]",
        },
        {
          label: "Box Price",
          value: "₹18,50,00,000",
          icon: Tag,
          bgClass: "bg-gradient-to-br from-[#bf953f] to-[#b38728]",
        },
        {
          label: "Expected Rental Yield",
          value: "8.4% – 9.2% p.a.",
          icon: TrendingUp,
          bgClass: "bg-gradient-to-br from-[#F97316] to-[#C2410C]",
        },
        {
          label: "Additional Charges",
          value: "Stamp Duty & Reg. extra",
          icon: Percent,
          bgClass: "bg-gradient-to-br from-[#8B5CF6] to-[#6D28D9]",
        },

      ],
      footer: {
        type: "split",
        left: "Additional Charges",
        right: "Excluding statutory taxes and stamp duty registration charges",
      },
    },
    "Pre-Leased": {
      title: "Pre-Leased Commercial Portfolio",
      headerIcon: TrendingUp,
      headerIconBg: "bg-amber-500",
      primaryAmountLabel: "EXISTING MONTHLY RENT",
      primaryAmount: "₹4.25L",
      primaryAmountColor: "text-emerald-600 dark:text-emerald-400",
      primaryDesc: "/mo",
      primarySub: "Assured Rental Cashflow",
      secondaryDarkCard: {
        label: "ANNUAL YIELD",
        value: "8.8%",
        valueColor: "text-amber-500",
        desc: "per annum",
      },
      details: [
        {
          label: "Is it Pre-Leased",
          value: "✓ Yes (Active)",
          icon: CheckCircle2,
          bgClass: "bg-gradient-to-br from-[#10B981] to-[#047857]",
        },
        {
          label: "Existing Tenant Company",
          value: "Accenture India Ltd.",
          icon: Users,
          bgClass: "bg-gradient-to-br from-[#F43F5E] to-[#BE123C]",
        },
        {
          label: "Tenant Category (Industry)",
          value: "IT & Global Tech",
          icon: Store,
          bgClass: "bg-gradient-to-br from-[#0EA5E9] to-[#0369A1]",
        },
        {
          label: "Existing Monthly Rent",
          value: "₹4,25,000 / mo",
          icon: Tag,
          bgClass: "bg-gradient-to-br from-[#10B981] to-[#047857]",
        },
        {
          label: "Existing Lease Tenure",
          value: "9 Years Long Term",
          icon: Calendar,
          bgClass: "bg-gradient-to-br from-[#8B5CF6] to-[#6D28D9]",
        },
        {
          label: "Remaining Tenure",
          value: "5 Yrs 4 Mos",
          icon: Clock,
          bgClass: "bg-gradient-to-br from-[#14B8A6] to-[#0F766E]",
        },
        {
          label: "Rent Escalation",
          value: "15% Escalation",
          icon: TrendingUp,
          bgClass: "bg-gradient-to-br from-[#F97316] to-[#C2410C]",
        },
        {
          label: "Rent Escalation Every",
          value: "Every 36 Months",
          icon: Calendar,
          bgClass: "bg-gradient-to-br from-[#bf953f] to-[#b38728]",
        },
      ],
      footer: {
        type: "split",
        left: "Investment Profile",
        right: "Grade A MNC tenant with locked-in bank guarantee deposit",
      },
    },
    Fractional: {
      title: "Fractional Commercial Ownership",
      headerIcon: BarChart2,
      headerIconBg: "bg-purple-500",
      primaryAmountLabel: "ASSURED MONTHLY RENT",
      primaryAmount: "₹45,000",
      primaryAmountColor: "text-[#0a1128] dark:text-white",
      primaryDesc: "/mo",
      primarySub: "Per Fractional Slot",
      secondaryDarkCard: {
        label: "ANNUAL YIELD",
        value: "9.2%",
        valueColor: "text-amber-500",
        desc: "per annum",
      },
      details: [
        {
          label: "Is it Pre-Leased",
          value: "✓ Yes Pre-Leased",
          icon: CheckCircle2,
          valueColor: "text-emerald-500",
          bgClass: "bg-gradient-to-br from-[#10B981] to-[#047857]",
        },
        {
          label: "Minimum Sq Ft",
          value: "400 sq.ft slot",
          icon: Maximize,
          bgClass: "bg-gradient-to-br from-[#3B82F6] to-[#1D4ED8]",
        },
        {
          label: "Assured Monthly Rent",
          value: "₹45,000 / month",
          icon: TrendingUp,
          bgClass: "bg-gradient-to-br from-[#F97316] to-[#C2410C]",
        },
        {
          label: "Annual Yield",
          value: "9.2% Net p.a.",
          icon: Percent,
          bgClass: "bg-gradient-to-br from-[#8B5CF6] to-[#6D28D9]",
        },
        {
          label: "Existing Tenant (Industry)",
          value: "Banking & Financial (BFSI)",
          icon: Briefcase,
          bgClass: "bg-gradient-to-br from-[#bf953f] to-[#b38728]",
        },
        {
          label: "Remarks",
          value: "Quarterly liquidity window available",
          icon: Tag,
          bgClass: "bg-gradient-to-br from-[#14B8A6] to-[#0F766E]",
        },
      ],
      footer: {
        type: "text-only",
        text: "Ideal for passive institutional & retail investors seeking verified yields.",
      },
    },
  },
} as const;
