import { Building, Store, ShoppingBag, Users, Briefcase } from "lucide-react";

export const listingsData = {
  headerIcon: Building,
  title: "Units & Floor Inventory",
  subtitle: "FEATURED REAL ESTATE SPACES (SUB LEASE & FULL LEASE)",
  listings: [
    {
      id: "ground-retail",
      unitNo: "Unit G-01",
      type: "Ground Floor · Retail Showroom",
      badge: "FULL LEASE",
      title: "High-Frontage Ground Floor Retail",
      builtUpArea: "1,450 sq.ft",
      carpetArea: "1,200 sq.ft",
      area: "1,200 sq.ft carpet",
      price: "₹1.2L/mo",
      perSqFt: "₹100/sq.ft",
      status: "Immediately Available",
      tentativeMonth: "Immediate",
      statusColor: "bg-emerald-500",
      icon: Store,
      colorTheme: {
        iconBg:
          "bg-emerald-600 text-white border-emerald-700/20 shadow-[0_2px_8px_rgba(5,150,105,0.35)]",
        leftBar: "bg-emerald-500",
        badge: "bg-emerald-500/10 text-emerald-700 border-emerald-500/30",
        priceText: "text-emerald-600",
      },
    },
    {
      id: "office-3rd",
      unitNo: "Suite #302",
      type: "3rd Floor · Plug & Play Office",
      badge: "SUB LEASE",
      title: "Furnished Sub Lease Office — 3rd Floor",
      builtUpArea: "4,200 sq.ft",
      carpetArea: "3,600 sq.ft",
      area: "3,600 sq.ft carpet",
      price: "₹3.06L/mo",
      perSqFt: "₹85/sq.ft",
      status: "Available in 30 Days",
      tentativeMonth: "Next Month",
      statusColor: "bg-blue-500",
      icon: Briefcase,
      colorTheme: {
        iconBg:
          "bg-blue-600 text-white border-blue-700/20 shadow-[0_2px_8px_rgba(37,99,235,0.35)]",
        leftBar: "bg-blue-500",
        badge: "bg-blue-500/10 text-blue-700 border-blue-500/30",
        priceText: "text-blue-600",
      },
    },
    {
      id: "showroom-1st",
      unitNo: "Unit #101-102",
      type: "1st Floor · Corporate Wing",
      badge: "FULL LEASE",
      title: "First Floor Glass Facade Wing",
      builtUpArea: "2,600 sq.ft",
      carpetArea: "2,200 sq.ft",
      area: "2,200 sq.ft carpet",
      price: "₹1.98L/mo",
      perSqFt: "₹90/sq.ft",
      status: "Immediately Available",
      tentativeMonth: "Immediate",
      statusColor: "bg-emerald-500",
      icon: ShoppingBag,
      colorTheme: {
        iconBg:
          "bg-violet-600 text-white border-violet-700/20 shadow-[0_2px_8px_rgba(124,58,237,0.35)]",
        leftBar: "bg-violet-500",
        badge: "bg-violet-500/10 text-violet-700 border-violet-500/30",
        priceText: "text-violet-600",
      },
    },
    {
      id: "coworking-6th",
      unitNo: "Entire 6th Floor",
      type: "6th Floor · Penthouse Floor",
      badge: "SUB LEASE",
      title: "Top Floor Managed Coworking & Lounge",
      builtUpArea: "5,400 sq.ft",
      carpetArea: "4,500 sq.ft",
      area: "4,500 sq.ft carpet",
      price: "₹3.82L/mo",
      perSqFt: "₹85/sq.ft",
      status: "Immediate Move-in",
      tentativeMonth: "Immediate",
      statusColor: "bg-emerald-500",
      icon: Users,
      colorTheme: {
        iconBg:
          "bg-rose-600 text-white border-rose-700/20 shadow-[0_2px_8px_rgba(225,29,72,0.35)]",
        leftBar: "bg-rose-500",
        badge: "bg-rose-500/10 text-rose-700 border-rose-500/30",
        priceText: "text-rose-600",
      },
    },
  ],
};
